cd "C:\Users\NickSherman\Dropbox\C64\AGC\AGC"
del "C:\Users\NickSherman\Dropbox\C64\AGC\AGC\Main.lst"
del "C:\Users\NickSherman\Dropbox\C64\AGC\AGC\Main.agc.bin"
del "C:\Users\NickSherman\Dropbox\C64\AGC\AGC\Main.bin"
del "C:\Users\NickSherman\Dropbox\C64\AGC\AGC\Main.agc.symtab"
del "C:\Users\NickSherman\Dropbox\C64\AGC\AGC\Main.bin.symtab"
"C:\Users\NickSherman\Downloads\VirtualAGC\bin\yaYUL" --html "Main.agc" >"Main.lst"
move "Main.agc.bin" "Main.bin"
move "Main.agc.symtab" "Main.bin.symtab"
