cd "/home/virtualagc/AGC_Game"
rm "/home/virtualagc/AGC_Game/Main.lst"
rm "/home/virtualagc/AGC_Game/Main.agc.bin"
rm "/home/virtualagc/AGC_Game/Main.bin"
rm "/home/virtualagc/AGC_Game/Main.agc.symtab"
rm "/home/virtualagc/AGC_Game/Main.bin.symtab"
"/home/virtualagc/VirtualAGC/bin/yaYUL" --html "Main.agc" >"Main.lst"
mv "Main.agc.bin" "Main.bin"
mv "Main.agc.symtab" "Main.bin.symtab"
